Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 4/7/2025
Var
a, b : inteiro


Inicio
escreva("Insira um número inteiro: ")
leia(a)
escreva("Insira um outro número: ")
leia(b)

se (a > b) entao
   escreva("O maior número é: ", a)
senao
     escreva("O maior número é: ", b)
fimse
Fimalgoritmo