Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 4/7/2025
Var
nota1, nota2 : real


Inicio
escreva("Informe a nota da primeira prova: ")
leia(nota1)
escreva("Informe a nota da segunda prova: ")
leia(nota2)

se ((nota1+nota2)/2) > 6 entao
   escreva("aluno aprovado!")
senao
     escreva("aluno reprovado!")
fimse

Fimalgoritmo