Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 4/14/2025
Var
cont, soma, num:inteiro
media: real


Inicio
soma  <- 0                                                     0
cont <- 0

enquanto (soma < 850) faca
         leia(num)
         soma <- soma + num
         cont <- cont + 1
fimenquanto

media <- soma/cont
escreva("Média = ",media)

Fimalgoritmo