Algoritmo "Ex3"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Leandro Junio dos Santos Colaes
// Data atual  : 4/16/2025
Var
n, i: inteiro

Inicio
//Entrada de dados
escreva("Informe um número")
leia(n)

//Informando os divisores
para i de 1 até n faca
     se (n%i = 0) entao
        escreva(i, " ")
     fimse
fimpara


Fimalgoritmo