Algoritmo "Ex4"
// 
//  
// Descrição   : Transformar nota númerica para Conceito
// Autor(a)    : Leandro Junio dos Santos Colaes
// Data atual  : 4/16/2025
Var
   nota: inteiro
   conc: caractere

Inicio
escreva("Informe a nota númerica: ")
leia(nota)

se (nota = 0) entao
   conc <- "E"
senao
   se (nota < 35) entao
      conc <- "D"
   senao
      se (nota < 60) entao


Fimalgoritmo